POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI1YmRlODU2YmVkN2E1ZDI2YzRiYWI0ZmQiLCJpYXQiOjE1NDEzMTQ4NjR9.bjEpfToEzDjjJNjad-Wo4Au7gqf1iB1X8g4Z1GilCns

{
    "title": "Tetststslhkljh",
    "author": "Keijo 3",
    "url": "http://test.com",
    "likes": 9,
    "userId": "5bde856bed7a5d26c4bab4fd"
}